// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvLTHYhdzQdCrJccu3IGVL5fBTfwCwjUI',
    appId: '1:324951000730:web:388c39d863baa036f0c123',
    messagingSenderId: '324951000730',
    projectId: 'nsbm-lms',
    authDomain: 'nsbm-lms.firebaseapp.com',
    storageBucket: 'nsbm-lms.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEb-SgJuIVggMX1mgBj11dbvbNOdMSclw',
    appId: '1:324951000730:android:9f1287ca770fa070f0c123',
    messagingSenderId: '324951000730',
    projectId: 'nsbm-lms',
    storageBucket: 'nsbm-lms.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFJ-OIJe1bXhBnUoD0tzNn1CBJGEwm7Ek',
    appId: '1:324951000730:ios:02fdd41fb0e3b2b2f0c123',
    messagingSenderId: '324951000730',
    projectId: 'nsbm-lms',
    storageBucket: 'nsbm-lms.appspot.com',
    iosClientId: '324951000730-c8kt764tklj4mca1j0mdmu19s44jcs8r.apps.googleusercontent.com',
    iosBundleId: 'com.ravinduPriyankara.nsbmLms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFJ-OIJe1bXhBnUoD0tzNn1CBJGEwm7Ek',
    appId: '1:324951000730:ios:02fdd41fb0e3b2b2f0c123',
    messagingSenderId: '324951000730',
    projectId: 'nsbm-lms',
    storageBucket: 'nsbm-lms.appspot.com',
    iosClientId: '324951000730-c8kt764tklj4mca1j0mdmu19s44jcs8r.apps.googleusercontent.com',
    iosBundleId: 'com.ravinduPriyankara.nsbmLms',
  );
}
